import numpy as np
import scipy
import torch
import pickle
import json

import sys
import os 
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../..')))

from reservoirgrid.models import Reservoir
from reservoirgrid.helpers import utils, viz, reservoir_tests, chaos_utils

path = "Examples\\Input_Discretization\\results\\Chaotic\\"
system_name = "LorenzLHS"
system_path = path + system_name

if not os.path.exists("Examples/Input_Discretization/Plots/3DPlots/" + system_name):
    os.makedirs("Examples/Input_Discretization/Plots/3DPlots/"+ system_name)

file_path = system_path + "/" + "10.0.pkl"

with open(file_path, "rb") as f:
    results = pickle.load(f)

# ==============================================================================
# ALIGNMENT LAYER: Sorts results to match Heatmap Indexing
# ==============================================================================
# Path to the legend generated by your heatmap script (using RMSE as a reliable reference)
legend_path = "Examples/Input_Discretization/Plots/HeatMaps/LorenzLHS/rmse_param_legend.json"

if os.path.exists(legend_path):
    print(f"Found heatmap metadata legend at {legend_path}. Aligning indices...")
    with open(legend_path, "r") as f:
        legend_data = json.load(f)
    
    # Map from hashable parameter tuple -> heatmap column index
    param_to_heatmap_idx = {}
    for entry in legend_data:
        combo_dict = entry["param_combo"]
        combo_tuple = tuple(sorted(combo_dict.items()))
        param_to_heatmap_idx[combo_tuple] = entry["col_idx"]
    
    # Sort the raw results list based on the heatmap column index mapping
    # Fallback to infinity if a parameter combination isn't found in the legend
    results = sorted(
        results, 
        key=lambda r: param_to_heatmap_idx.get(tuple(sorted(r["parameters"].items())), float('inf'))
    )
else:
    print("WARNING: Heatmap legend JSON not found! Indices will remain misaligned.")
    print("Please run your heatmap generation script first to generate the metadata.")
# ==============================================================================

metrics_dict = {
    "KL Divergence": [chaos_utils.kl_divergence(r["true_value"], r["predictions"]) for r in results],
    "JS Divergence": [chaos_utils.js_divergence(r["true_value"], r["predictions"]) for r in results],
    "RMSE": [utils.RMSE(r["true_value"], r["predictions"]) for r in results]
}

viz.plot_multidimensional_3d(
    results, 
    "Lorenz-LHS", 
    pp = 10, 
    metrics_dict = metrics_dict, 
    save_html=False, 
    path="Examples/Input_Discretization/Plots/3DPlots/" + system_name + "/"
).show()